name: mpm-lecture
channels:
  - conda-forge
dependencies:
  - python=3.13
  - pip
  - numpy>=2.1
  - matplotlib>=3.10
  - sympy
  - scipy
  - scikit-image
  - panda
  - emoji
  - pip:
      - -e . # install local repo
